Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: kb-fc-
    SupplierDeployMetadata:
      DeployTimeout: 7200
    TemplateConfigs:
      - Name: FC部署
        Url: 'ros_templates/template.yaml'
        AllowedRegions: []
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: kodbox基于FC部署demo
    Image: 'resources/icons/kodbox_log.png'
    Name: Kodbox-FC部署版
  ShareType: Public
  ApprovalType: Manual