Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    AllowedRegions:
      - cn-hangzhou
      - cn-beijing
      - cn-shanghai
      - ap-southeast-1
    ServiceInstanceNameRule:
      Prefix: kb-fc-
    SupplierDeployMetadata:
      DeployTimeout: 7200
    TemplateConfigs:
      - Name: FC部署
        Url: 'ros_templates/template.yaml'
        ArchitectureDiagramUrl: 'https://service-info-public.oss-cn-hangzhou.aliyuncs.com/1563457855438522/service-image/architecture.png'
        AllowedRegions:
          - cn-hangzhou
          - cn-beijing
          - cn-shanghai
          - ap-southeast-1
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: kodbox基于FC部署demo
    Image: 'resources/icons/kodbox_log.png'
    Name: Kodbox-FC部署版
  ShareType: Public
  ApprovalType: Manual